Quiet test run and make passing tests more obvious.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,13 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 cd "`dirname \"$0\"`/.."
 
-cd test/
+cd test
+
+# runs a test file with PASS/FAIL message
+run_test() {
+  php $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+}
 
 if [ "$1" == "" ]; then
   for test in $(ls *.php); do
-    php $test
+    run_test $test
   done
 else
-  php $1.php
+  run_test $1.php
 fi
