Minor fixes to scripts.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -e
-cd "`dirname \"$0\"`/.."
+cd "$(dirname "$0")/.."
 
 # check dependencies
 which php > /dev/null      || (echo "php must be installed"; exit 1)
@@ -12,13 +12,13 @@ cd test
 
 # runs a test file with PASS/FAIL message
 run_test() {
-  php $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+  (php "$1" && echo "PASS $1") || (echo "FAIL $1"; exit 1)
 }
 
 if [ "$1" == "" ]; then
-  for test in $(ls *.php); do
-    run_test $test
+  for test in *.php; do
+    run_test "$test"
   done
 else
-  run_test $1.php
+  run_test "$1.php"
 fi
